### ISSUE TITLE
Any update on the encryption?

### ISSUE THREAD

**Issue by niobos** [SlightlyLoony/SolarEdgeMonitor#1]
Hi,

I'm very interested in this project. Any updates on this? From the readme, I deduce that the traffic was plaintext, and they switched to Encrypted. Is that correct?

**Comment by SlightlyLoony** [comment]
Your deduction is correct, unfortunately for both of us.  I never got an official response from Solar Edge, but a local tech told me that once their monitoring is fully provisioned after an installation, they switch to encrypted traffic.

**Comment by nielslaukens** [comment]
that's bad news for me... Thank you for your answer!

**Comment by niobos** [comment]
that's bad news for me... Thank you for your answer!
